version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: productdb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Omkar@321
      MYSQL_DATABASE: productdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: product-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/productdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Omkar@321
      APP_JWT_SECRET: zestindia-super-secret-jwt-key-2026-product-api-secure
      APP_JWT_EXPIRATION: 86400000
      APP_JWT_REFRESH_EXPIRATION: 604800000
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: